FROM alpine:edge

# lsd is in testing repo
RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk update

# Base
RUN apk add zsh git

# LunarVim requirements
RUN apk add neovim make py3-pip npm nodejs cargo

RUN apk add vim

# tools
RUN apk add curl bat fd make lsd ripgrep zoxide openssh tmux delta bash

# required for usermod
RUN apk add shadow
RUN usermod -s /bin/zsh root

#RUN adduser -D -s /bin/zsh user
#USER user
#WORKDIR /home/user
WORKDIR /root

#ADD --chown=user:user --chmod=770 install.sh /home/user
ADD --chmod=770 install.sh /root

RUN ./install.sh

