FROM alpine:edge

# lsd is in testing repo
RUN echo "https://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
RUN apk update

# Base
RUN apk add zsh git

# LunarVim requirements
RUN apk add neovim make py3-pip npm nodejs cargo

# Testing .vimrc for using vim on systems packages cannot be installed
RUN apk add vim

# tools
RUN apk add curl bat fd make lsd ripgrep zoxide openssh tmux delta bash dust fzf

# Run as root
# required for usermod
# RUN apk add shadow
# RUN usermod -s /bin/zsh root
# WORKDIR /root
# ADD --chmod=770 install.sh /root

# Run as user
RUN apk add sudo
RUN echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/wheel_nopasswd
RUN adduser -D -s /bin/zsh user
# required for usermod
RUN apk add shadow
RUN usermod -aG wheel user
USER user
WORKDIR /home/user
ADD --chown=user:user --chmod=770 install.sh /home/user

RUN ./install.sh

CMD [ "/bin/zsh" ]
